// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LoreVS
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string LoreVSString = "75c63f82-bb45-456a-be72-19ad0c8e33b4";
        public static Guid LoreVS = new Guid(LoreVSString);

        public const string guidWorkspaceExplorerToolWindowPackageCmdSetString = "cfb400f1-5c60-4f3c-856e-180d28def0b7";
        public static Guid guidWorkspaceExplorerToolWindowPackageCmdSet = new Guid(guidWorkspaceExplorerToolWindowPackageCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int LoreFileGroup = 0x0006;
        public const int LoreFileContextGroup = 0x0007;
        public const int LoreFileSubMenu = 0x0008;
        public const int LoreContextGroup = 0x0002;
        public const int LoreSubMenu = 0x0003;
        public const int LoreChangesToolbar = 0x0004;
        public const int LoreChangesToolbarGroup = 0x0005;
        public const int LoreChangesBranchGroup = 0x000A;
        public const int AddToLoreCommand = 0x0101;
        public const int CommitToLoreCommand = 0x0102;
        public const int CloneCommand = 0x0103;
        public const int IgnoreAndUntrackCommand = 0x010B;
        public const int UndoChangesCommand = 0x010C;
        public const int CompareUnmodifiedCommand = 0x010D;
        public const int PullCommand = 0x0108;
        public const int PushCommand = 0x0109;
        public const int RefreshChangesCommand = 0x010A;
        public const int BranchCommand = 0x010E;
        public const int idmWSE_ContextMenu = 0x0002;
    }
}
