// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LoreVS
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string LoreVSString = "75c63f82-bb45-456a-be72-19ad0c8e33b4";
        public static Guid LoreVS = new Guid(LoreVSString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int AddToLoreCommand = 0x0101;
        public const int CommitToLoreCommand = 0x0102;
        public const int StartLoreServerCommand = 0x0103;
        public const int StopLoreServerCommand = 0x0104;
        public const int InstallLoreToolsCommand = 0x0105;
        public const int MyCommand = 0x0106;
    }
}
